Minor cleanup of depreactions
gustavkarlsson/koptional pull request #3
Opened 2020-10-09 11:48 UTC by StefMa

As discussed in #2 `valueUnsafe` shouldn't be used. 
There are better functions for them.

Beside of that I removed an 1 year old deprecated function. I think this is okay 😇

2020-10-09 12:12 UTC, gustavkarlsson requested changes
Thx for the contribution!

2020-10-09 12:12 UTC, gustavkarlsson commented on lib/src/main/kotlin/se/gustavkarlsson/koptional/Optional.kt
> +    @Deprecated(message = "Unsafe to use. Use `ifPresent` or `ifAbsent` instead")
`ifPresent` and `ifAbsent` are not really alternatives to `valueUnsafe` . They are rather alternatives to use cases that might use `valueUnsafe`.

I would change it to just "Useless" and add `ReplaceWith("value!!")` or something like that.

2020-10-11 17:10 UTC, gustavkarlsson approved these changes

2020-10-11 17:13 UTC, gustavkarlsson requested changes
Missing comma ;)

2020-10-11 17:13 UTC, gustavkarlsson commented on lib/src/main/kotlin/se/gustavkarlsson/koptional/Optional.kt
> +        replaceWith = ReplaceWith("value!!")
```suggestion
        message = "Useless",
        replaceWith = ReplaceWith("value!!")
```

2020-10-11 17:30 UTC, StefMa commented
🤦 Thanks

2020-10-11 17:35 UTC, merged